spring:
  jersey:
    type: filter
    filter:
      order: 2147483647

management:
  zookeeper:
    clusters:
      - datacenter: dc
        root: /run/hermes
        connectionString: zk:2181
  kafka:
    clusters:
      - datacenter: dc
        clusterName: primary-dc
        connectionTimeout: 3000
        brokerList: kafka:29092
  endpoints:
    web:
      base-path: /
  rest-template:
    connect-timeout: 2000
    read-timeout: 2000
  backend:
    port: 8090
    servlet:
      context-path: /
  health:
    enabled: true
  consumer-groups:
    create-manually: true
  leadership:
    zookeeper-dc: dc
  audit.enabled: false
  cache:
    topicOwnerRefreshRateInSeconds: 300 # 5 minutes
    subscriptionOwnerRefreshRateInSeconds: 300
  schema.repository:
    type: schema_registry
    serverUrl: http://schema-registry:8081
    validationEnabled: true
  prometheus:
    client:
      enabled: true
      externalMonitoringUrl: http://prometheus:8428
