zookeeper:
  enabled: false

storage:
  pathPrefix: /run/hermes
  clusters:
    - datacenter: dc
      root: /run/hermes
      connectionString: zk:2181

kafka:
  clusters:
    - datacenter: dc
      clusterName: primary
      connectionTimeout: 3000
      bootstrapKafkaServer: kafka:29092

server:
  port: 8090

spring:
  jersey:
    type: filter
    filter:
      order: 2147483647

management:
  endpoints:
    web:
      base-path: /
  rest-template:
    connect-timeout: 2000
    read-timeout: 2000
  server:
    servlet:
      context-path: /
  health:
    periodSeconds: 30
    enabled: true
  consumer-groups:
    create-manually: true
  leadership:
    zookeeper-dc: dc


audit.enabled: false

topicOwnerCache:
  refreshRateInSeconds: 300 # 5 minutes

subscriptionOwnerCache:
  refreshRateInSeconds: 300

schema.repository:
  type: schema_registry
  serverUrl: http://schema-registry:8081
  validationEnabled: true

prometheus:
  client:
    enabled: true
    externalMonitoringUrl: http://prometheus:8428

console:
  configurationLocation: console/config-local.json
  configurationType: classpath_resource
