frontend:
  startup:
    topic:
      loading:
        metadata:
          enabled: true
        schema:
          enabled: true
  schema:
    cache:
      refreshAfterWriteMinutes: 1
  ssl:
    enabled: true
    port: 18443
  server:
    port: 18080
    http2Enabled: true
  handlers:
    idleTimeout: 2000
  metrics:
    graphiteReporterEnabled: true
    reportPeriod: 1
  graphite:
    port: 18023
  zookeeper:
    connectionString: "localhost:14192"
    connectionTimeout: 10000
    sessionTimeout: 10000
    authorization:
      enabled: false
      user: admin
      password: admin
  kafka:
    producer:
      retryBackoffMs: 100

