frontend:
  zookeeper:
    clusters:
      - datacenter: "dc"
        root: "/run/hermes"
        connectionString: "zk:2181"
  kafka:
    clusters:
      - datacenter: "dc"
        brokerList: "kafka:9092"
  graphite:
    host: "graphite"
  metrics:
    graphiteReporterEnabled: true
  schema:
    cache:
      refreshAfterWriteMinutes: 1
    repository:
      serverUrl: "http://schema-registry:8081"