zookeeper:
  enabled: false


storage:
  clusters:
    -
      datacenter: dc
      clusterName: zk
      connectionString: localhost:2181

kafka:
  clusters:
    -
      datacenter: dc
      clusterName: primary
      connectionTimeout: 3000
      bootstrapKafkaServer: localhost:9092

spring:
  jersey:
    type: filter

server:
  port: 8090

management:
  endpoints:
    web:
      base-path: /
  rest-template:
    connect-timeout: 2000
    read-timeout: 2000
  server:
    servlet:
      context-path: /
  health:
    periodSeconds: 30
    enabled: true

audit.enabled: false

topicOwnerCache:
  refreshRateInSeconds: 300 # 5 minutes

subscriptionOwnerCache:
  refreshRateInSeconds: 300

console:
  configurationLocation: console/config-local.json
  configurationType: classpath_resource
