zookeeper:
  enabled: false

kafka:
  clusters:
    -
      clusterName: primary
      connectionString: localhost:2181
      connectionTimeout: 3000

storage:
  connectionString: localhost:2181
  connectionTimeout: 3000

spring:
  jersey:
    type: servlet

server:
  port: 8090
  servlet-path: /status

management:
  context-path: /
  restTemplate:
    connect-timeout: 2000
    read-timeout: 2000

schema.repository.type: schema_registry

audit.enabled: false